changelog:
  exclude:
    labels:
      - skip-changelog
    authors:
      - github-actions
      - sourcery-ai
      - coderabbitai
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: New Features
      labels:
        - feature
        - enhancement
    - title: Bug Fixes
      labels:
        - bug
        - fix
    - title: Other Changes
      labels:
        - "*"